### ISSUE TITLE
Better ordering/overview in lecture list

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#29]
**Is your feature request related to a problem? Please describe.**
Currently we display lectures in an order which does not make sense

**Describe the solution you'd like**
Rework the whole lecture list

**Describe alternatives you've considered**
We could also add an archive collapsible which would mitigate bad ux and require less work

**Comment by meffmadd** [comment]
Could you specify what about the current ordering that does not make sense? Maybe we should add a dropdown to specify ordering in the frontend.

**Comment by florian-jaeger** [comment]
We show lectures from old to new.

**Comment by meffmadd** [comment]
I would say the order is actually not from old to new but the order when they were first added since we do not actually store any creation or modification timestamps. I guess the actual order based on time should be the time of their activation, not the time they were added to the database (based on id). But for me, the temporal order is not so important (the older lectures could get assignments first so could be more important to display). In my opinion, lexicographical or "something new happened" ordering is more important to the user.

For this, we would need creation and modification timestamps which would come in handy anyway.
