### ISSUE TITLE
LTI Sync Grades

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#45]
**Is your feature request related to a problem?**
Currently instructors have to manually enter score in our moodle courses.

**Describe the solution you'd like**
We could use the entrypoints of the LTI [specification](http://www.imsglobal.org/spec/lti/v1p3/) to sync grades to courses.

**Additional context**
This feature will only work for lectures that use the [LTI13OAuthenticator](https://github.com/TU-Wien-dataLAB/lti13oauthenticator).

**Comment by Paul2708** [comment]
> This feature will only work for lectures that use the [LTI13OAuthenticator](https://github.com/TU-Wien-dataLAB/lti13oauthenticator).

Is this still the case? If so, do you think it's feasible to implement an LTI sync without the LTI authenticator? Unfortunately, I'm not that familiar with LTI. Since we are not using the LTI authenticator, the instructor must somehow provide the [necessary configuration attributes](https://github.com/TU-Wien-dataLAB/grader-service/blob/16a57802a20bffc42206e2dab4ed22a99c4bdb1a/grader_service/plugins/lti.py#L28), right? However, since we never authenticated the instructor against the LMS, this is probably not working.
