### ISSUE TITLE
Refactor git lookup

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#71]

**Comment by adammccartney** [comment]
So it felt like I made a little bit of progress with this over the past couple of days,  today I pushed sha 5163fecea67308c1da0f0017bb1208201ef84877 with the most recent updates. Since making specific dataclasses for the various types of git repos, I had some further thoughts on how to deal with the very many calls to `os.path.join(...)` that are getting made all over the place still. 


I was wondering what would be the implication of implementing `__repr__` methods on each of our `GitRepo` classes that we now have. This would mean that we can simple call `os.path(str(git_repo))` when we want to create the specific path. Instead of having to always call `os.path.join(git_repo.root, git_repo.lecture_code, git_repo.assignment_id)`. I pushed a quick edit of these classes and they now look like this: https://github.com/TU-Wien-dataLAB/Grader-Service/blob/a21e63507f5c9009b823836bda99cfb118b175af/grader_service/grader_service/handlers/git/server.py#L29-L64

As I mentioned in the commit, I haven't tested them yet and also somehow I am not convinced that I've got the representation of the paths quite right - my inclusion of the `self.root` is possibly superfluous. I think the actually creation of the paths on the system is being done by `GraderBaseHandler.construct_git_dir()`. I'm not sure, but this seems to me that it might be happier living with the other git specific methods in `GitBaseHandler`. It also appears as if we are stripping and then re-appending the `git` pathlet in between receiving the request and setting up the path on our filesystem.
